import { FlightType } from 'src/types/redux/flights';
import { LocationsType, HotelType } from 'src/types/redux/hotels';

export const flights: FlightType[] = [
  {
    id: 1,
    airline: 'Airline A',
    departureLocation: 'New York',
    arrivalLocation: 'Paris',
    departureTime: '10:00 AM',
    duration: '2h 30m',
    price: 299,
    destinationId: 1,
  },
  {
    id: 2,
    airline: 'Airline B',
    departureLocation: 'Los Angeles',
    arrivalLocation: 'Tokyo',
    departureTime: '1:30 PM',
    duration: '3h 15m',
    price: 349,
    destinationId: 1,
  },
  {
    id: 3,
    airline: 'Airline C',
    departureLocation: 'Chicago',
    arrivalLocation: 'London',
    departureTime: '4:45 PM',
    duration: '1h 45m',
    price: 199,
    destinationId: 1,
  },
  {
    id: 1,
    airline: 'Airline A',
    departureLocation: 'New York',
    arrivalLocation: 'Paris',
    departureTime: '10:00 AM',
    duration: '2h 30m',
    price: 299,
    destinationId: 2,
  },
  {
    id: 2,
    airline: 'Airline B',
    departureLocation: 'Los Angeles',
    arrivalLocation: 'Tokyo',
    departureTime: '1:30 PM',
    duration: '3h 15m',
    price: 349,
    destinationId: 2,
  },
  {
    id: 3,
    airline: 'Airline C',
    departureLocation: 'Chicago',
    arrivalLocation: 'London',
    departureTime: '4:45 PM',
    duration: '1h 45m',
    price: 199,
    destinationId: 2,
  },
  {
    id: 1,
    airline: 'Airline A',
    departureLocation: 'New York',
    arrivalLocation: 'Paris',
    departureTime: '10:00 AM',
    duration: '2h 30m',
    price: 299,
    destinationId: 3,
  },
  {
    id: 2,
    airline: 'Airline B',
    departureLocation: 'Los Angeles',
    arrivalLocation: 'Tokyo',
    departureTime: '1:30 PM',
    duration: '3h 15m',
    price: 349,
    destinationId: 3,
  },
  {
    id: 3,
    airline: 'Airline C',
    departureLocation: 'Chicago',
    arrivalLocation: 'London',
    departureTime: '4:45 PM',
    duration: '1h 45m',
    price: 199,
    destinationId: 3,
  },
];

export const locations: LocationsType[] = [
  {
    id: '1',
    name: 'Hà Nội',
    description: 'Thủ đô ngàn năm văn hiến với nhiều điểm tham quan hấp dẫn.',
    image_url: '/assets/hanoi.jpeg',
  },
  {
    id: '2',
    name: 'Đà Nẵng',
    description: 'Thành phố đáng sống với biển đẹp và nhiều cây cầu nổi tiếng.',
    image_url: '/assets/danang.jpeg',
  },
  {
    id: '3',
    name: 'TP. Hồ Chí Minh',
    description: 'Thành phố sôi động nhất Việt Nam, trung tâm kinh tế và giải trí.',
    image_url: '/assets/hcm.jpeg',
  },
  {
    id: '4',
    name: 'Nha Trang',
    description: 'Thành phố biển với những bãi biển trong xanh và các khu nghỉ dưỡng.',
    image_url: '/assets/nt.jpeg',
  },
];
export const hotels: HotelType[] = [
  {
    id: '1',
    name: 'Khách sạn Metropole',
    location_id: '1',
    description: 'Khách sạn sang trọng nằm ở trung tâm Hà Nội.',
    rating: 5,
    image_url: '/assets/danang.jpeg',
  },
  {
    id: '2',
    name: 'Khách sạn Novotel',
    location_id: '2',
    description: 'Khách sạn hiện đại gần bãi biển Đà Nẵng.',
    rating: 4,
    image_url: '/assets/danang.jpeg',
  },
  {
    id: '3',
    name: 'Khách sạn Rex',
    location_id: '3',
    description: 'Khách sạn lịch sử nổi tiếng ở trung tâm TP. Hồ Chí Minh.',
    rating: 5,
    image_url: '/assets/danang.jpeg',
  },
  {
    id: '4',
    name: 'Khách sạn Vinpearl Resort',
    location_id: '4',
    description: 'Khu nghỉ dưỡng cao cấp nằm bên bờ biển Nha Trang.',
    rating: 5,
    image_url: '/assets/danang.jpeg',
  },
];

export const rooms = [
  {
    id: '1',
    hotel_id: '1',
    image_url: '/assets/danang.jpeg',
    name: 'Phòng Deluxe',
    price: '1000000',
    description: 'Phòng với view đẹp, tiện nghi cao cấp.',
    availability: true,
    maxGuests: 2, // Tối đa 2 người
  },
  {
    id: '2',
    hotel_id: '1',
    image_url: '/assets/danang.jpeg',
    name: 'Phòng Standard',
    price: '800000',
    description: 'Phòng cơ bản với đầy đủ tiện nghi.',
    availability: true,
    maxGuests: 2, // Tối đa 2 người
  },
  {
    id: '3',
    hotel_id: '2',
    image_url: '/assets/danang.jpeg',
    name: 'Phòng Suite',
    price: '1500000',
    description: 'Phòng hạng sang với dịch vụ VIP.',
    availability: false,
    maxGuests: 3, // Tối đa 3 người
  },
  {
    id: '4',
    hotel_id: '3',
    image_url: '/assets/danang.jpeg',
    name: 'Phòng Deluxe',
    price: '1200000',
    description: 'Phòng sang trọng với phong cách cổ điển.',
    availability: true,
    maxGuests: 2, // Tối đa 2 người
  },
  {
    id: '5',
    hotel_id: '3',
    image_url: '/assets/danang.jpeg',
    name: 'Phòng Suite',
    price: '1800000',
    description: 'Phòng rộng rãi với đầy đủ dịch vụ cao cấp.',
    availability: false,
    maxGuests: 4, // Tối đa 4 người
  },
  {
    id: '6',
    hotel_id: '4',
    image_url: '/assets/danang.jpeg',
    name: 'Phòng Deluxe hướng biển',
    price: '2500000',
    description: 'Phòng với tầm nhìn ra biển và dịch vụ cao cấp.',
    availability: true,
    maxGuests: 2, // Tối đa 2 người
  },
  {
    id: '7',
    hotel_id: '4',
    image_url: '/assets/danang.jpeg',
    name: 'Phòng Suite hướng biển',
    price: '3500000',
    description: 'Phòng Suite cao cấp với tầm nhìn đẹp và dịch vụ riêng biệt.',
    availability: false,
    maxGuests: 4, // Tối đa 4 người
  },
];
