# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - travel-socical-fe

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install deps (yarn)
        run: yarn install --frozen-lockfile

      - name: Build (if present)
        run: yarn build || echo "No build script, skipping."

      - name: Test (if present)
        run: yarn test || echo "No test script, skipping."

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C8F7A8BE6BD747CD97EE7E2FBBF9FA1E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_97B780B9CB714D5BB342668C3BD30879 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_600B09ECB8B34B0C82D33D9C82BFCCC7 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'travel-socical-fe'
          slot-name: 'Production'
          package: .


